doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    types:
      notification_id: 'App\Notifications\Infrastructure\Persistence\Doctrine\ORM\NotificationIdType'
      # Clients
      address_type: 'App\Clients\Infrastructure\Persistence\Doctrine\ORM\AddressInUsaType'
      client_id: 'App\Clients\Infrastructure\Persistence\Doctrine\ORM\ClientIdType'
      date_of_birth_type: 'App\Clients\Infrastructure\Persistence\Doctrine\ORM\DateOfBirthType'
      email_type: 'App\Clients\Infrastructure\Persistence\Doctrine\ORM\EmailType'
      fico_type: 'App\Clients\Infrastructure\Persistence\Doctrine\ORM\FicoType'
      phone_number_type: 'App\Clients\Infrastructure\Persistence\Doctrine\ORM\PhoneNumberType'
      ssn_type: 'App\Clients\Infrastructure\Persistence\Doctrine\ORM\SsnType'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Clients:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Clients/Infrastructure/Persistence/Doctrine/ORM'
        prefix: 'App\Clients\Domain'
        alias: Clients
      Notifications:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Notifications/Domain'
        prefix: 'App\Notifications\Domain'
        alias: Notifications

#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
