framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus:
            event.bus:
                default_middleware: allow_no_handlers

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        #failure_transport: failed

        # https://symfony.com/doc/current/messenger.html#transport-configuration
        transports:
          events:
            dsn: '%env(RABBIT_EVENTS_QUEUE_DSN)%'
            options:
              verify: false
              queues:
                events:
                  arguments:
                    x-queue-type: 'quorum'
#            some-async: #  TODO CHANGE ME
#                dsn: '%env(RABBIT_QUEUE_QUEUE_NAME)%' #  TODO CHANGE ME
#                options:
#                    verify: false
#                    queues:
#                        queue_name: # TODO CHANGE ME!
#                            arguments:
#                                x-queue-type: 'quorum'
#
#
#            failed: 'doctrine://default?queue_name=failed'
            #sync: 'sync://'

        routing:
          App\Shared\Domain\Event\EventInterface: events
            #'App\SomeNamespaceCommand\': some-async # TODO CHANGE ME
