monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: nested
      buffer_size: 50
    nested:
      type: rotating_file
      path: "/var/log/app/debug.log"
      level: debug
      formatter: 'monolog.formatter.logstash'
      max_files: 3
    console:
      type: console
      process_psr_3_messages: false
      channels: [ "!event", "!doctrine" ]

    # Новый обработчик для excluded_http_codes и excluded_404s
    excluded_handler:
      type: fingers_crossed
      action_level: error
      handler: nested
      excluded_http_codes: [ 404, 405 ]

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
        channels: [ "!event" ]
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!console" ]

when@test:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
        channels: [ "!event" ]
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!console" ]

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: notice
        handler: nested
        excluded_http_codes: [ 404, 405 ]
        buffer_size: 50 # How many messages should be saved? Prevent memory leaks
      nested:
        type: stream
        path: php://stderr
        level: notice
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine" ]

