controllers:
  resource: ../src/Shared/Infrastructure/API/Controller/
  type: annotation

kernel:
  resource: ../src/Shared/Infrastructure/Kernel.php
  type: annotation


clients:
  resource: ../src/Clients/Infrastructure/API/V1/Controller/
  type: annotation

creditRequests:
  resource: ../src/Credit/CreditRequests/Infrastructure/API/V1/Controller/
  type: annotation